services:
  app:
    # build: .
    image: duanyll/hairclipv2:latest
    ports:
      - 7860:7860
    depends_on:
      - db
    environment:
      - CACHE_TIME=3600
      - REDIS_HOST=db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: python server.py
    # The -it flag is necessary to prevent stucking in startup. I don't know why. 
    stdin_open: true
    tty: true
  db:
    image: redis:latest
    ports:
      - 6379:6379